# The header file is useless here!
# This is a library!
# header file made for consumers only!
all:
	gcc -c ExtremeC_examples_chapter3_2_trigon.c -o trigon.o
	gcc -c ExtremeC_examples_chapter3_2_2d.c -o 2d.o
	gcc -c ExtremeC_examples_chapter3_2_3d.c -o 3d.o
